name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2
      with:
        persist-credentials: false
    - uses: actions/setup-python@v5.3.0
      with:
        python-version: '3.14'
          # cache: 'pipenv' # caching pipenv dependencies
    - name: Install poetry and pipx
      run: |
        pip install pipx && pip install uv && pipx install uv && uv sync

    - name: Run Makefile
      run: make check
    - name: Run make
      run: uv run hatch publish
    - name: Upload Package
      uses: actions/upload-artifact@v4.5.0
      with:
        name: packages
        path: dist/
        if-no-files-found: error
        retention-days: 1

